### ISSUE TITLE
Fakespot Changing Result Order

### ISSUE THREAD

**Issue by rufusrock** [rufusrock/scraping_tools#9]
![fakespot_ab_test_1](https://user-images.githubusercontent.com/103443455/228865333-a7ecca5b-497f-47da-b6bb-8d262cd32960.png)

**It seems like fakespot is manipulating the order of results.** 

Different Ad Types are rearranged differently. 

![banner_ad_diff](https://user-images.githubusercontent.com/103443455/228865483-5f351165-e4ee-475c-be49-d6541b80c592.png)

![search_injected_diff](https://user-images.githubusercontent.com/103443455/228865566-56def0b3-1023-4907-8846-76d1026af034.png)

![video_ad_diff](https://user-images.githubusercontent.com/103443455/228865648-baee1a07-5b73-4bb5-8e3c-bf43996aa5f6.png)

![carousel_ad_diff](https://user-images.githubusercontent.com/103443455/228865677-ab232d73-c637-4bb7-8de6-77e50af9bb8e.png)

Wondering whether it is possible to reverse engineer the fakespot rearranging algorithm - or would have to rescrape the whole dataset.

**Comment by bramtayl** [comment]
Nice graphs! Well, for one, Fakespot inserts stuff into the window, so it's not too surprising to me that the y-coordinates would change a bit. The carousel ads one is a bit stark though. The "sort by fakespot grade" setting is turned off by default, and assuming you aren't changing that, then I don't think there's anything to do here except to run it once with Fakespot turned on and once with Fakespot turned off. It's probably good to do anyway as a robustness check. And by the way, I strongly suspect we'll have to scrape again a few more times yet with more modifications, because I don't think there was ever a firm plan about what to do with the data anyways. I'm a fan of the "collect a bit of data, play around with it, collect the rest" strategy, but too late for that now, sorry.
